export const BorrowersActionType = {
    FETCH_BORROWERS_START: 'FETCH_BORROWERS_START',
    FETCH_BORROWERS_SUCCESS: 'FETCH_BORROWERS_SUCCESS',
    FETCH_BORROWERS_FAILURE: 'FETCH_BORROWERS_FAILURE',
}